services:
  rethinkdb:
    image: rethinkdb:2.4.3
    hostname: rethinkdb
    networks:
      - stf-net

  stf:
    image: devicefarmer/stf:latest
    hostname: stf
    depends_on:
      - rethinkdb
    command: >
      stf local
        --public-ip stf
        --adb-host host.docker.internal
        --adb-port 5037
    ports:
      - "7100:7100"
    environment:
      - RETHINKDB_PORT_28015_TCP=tcp://rethinkdb:28015
    networks:
      - stf-net

networks:
  stf-net:
    driver: bridge